config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :cats
  root "pages#home"
  get 'about', to: 'pages#about'

  get 'login', to: 'sessions#new'       # For displaying the login form
  post 'login', to: 'sessions#create'   # For submitting the login form
  delete 'logout', to: 'sessions#destroy'  # For logging out the user
  
  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
class Cat < ApplicationRecord
    belongs_to :user
    
    validates :name, presence: true, length: { minimum: 3, maximum: 100 }
    validates :color, presence: true
end
  

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :cats, dependent: :destroy

    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: { maximum: 105 },format: {with:VALID_EMAIL_REGEX}
    validates :password, confirmation: true

    has_secure_password
end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
  helper_method :current_user,:logged_in?

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]
  before_action :require_login, only: %i[new edit create update destroy]

  # GET /cats or /cats.json
  def index
    @cats = Cat.page(params[:page]).per(5)
  end

  # GET /cats/1 or /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats or /cats.json
  def create
    @cat = Cat.new(cat_params)
    @cat.user = current_user
    if @cat.save
      flash[:success] = "Cat was successfully created."
      redirect_to @cat
    else
      render :new
    end
  end

  # PATCH/PUT /cats/1 or /cats/1.json
  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      flash[:success] = "Cat was successfully updated."
      redirect_to @cat
    else
      render :edit
    end
  end

  # DELETE /cats/1 or /cats/1.json
  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy
    flash[:success] = "Cat was successfully deleted."
    redirect_to cats_url
  end

  private
    def require_login
      unless logged_in?
        flash[:alert] = "You must be logged in to access this section"
        redirect_to login_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cat_params
      params.require(:cat).permit(:name, :color)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to cats_path if logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_login, only: %i[destroy]

    def new

    end

    def create
        user = User.find_by(username: params[:session][:username])
        if user && user.authenticate(params[:session][:password])  
            session[:user_id] = user.id  
            flash[:notice] = "Logged in successfully, #{user.username}!."
            redirect_to user_path(user)  
        else
            flash.now[:alert] = "There was something wrong with your login details."
            render :new, status: :unprocessable_entity
        end
    end
    
    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out!"
        redirect_to root_path
    end

    private
    def require_login
        unless logged_in?
          flash[:alert] = "You must be logged in to access this section"
          redirect_to login_path
        end
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :require_login, only: %i[ index show edit update destroy ]
  include UsersHelper

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show

  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id  
        flash[:notice] = "Welcome to the Ruby Demo, #{@user.username}! You have successfully signed in."
        format.html { redirect_to cats_path }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:notice] = "Your account information was successfully updated"
        format.html { redirect_to cats_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def require_login
      unless logged_in?
        flash[:alert] = "You must be logged in to access this section"
        redirect_to login_path
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
          rescue ActiveRecord::RecordNotFound
      redirect_to users_path, alert: "User not found."
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/cats_helper.rb
module CatsHelper
    def valid_css_color?(color)
        css_colors = ["aqua", "black", "blue", "fuchsia", "gray", "green", "lime", "maroon", "navy", "olive", "purple", "red", "silver", "teal", "white", "yellow"]
        css_colors.include?(color.downcase) || color.match?(/\A#(?:[0-9a-fA-F]{3}){1,2}\z/)
      end
    
      def display_color_block(color)
        if valid_css_color?(color)
          content_tag(:div, '', style: "background-color: #{color}; width: 20px; height: 20px; border: 1px solid #000;")
        else
          content_tag(:div, 'N/A', style: "width: 20px; height: 20px; border: 1px solid #000; line-height: 20px; text-align: center;")
        end
      end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, size: 150) 
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
      image_tag(gravatar_url, alt: user.username, class: "gravatar rounded shadow mx-auto p-2", style: "border: none;")
    end
end
  

app/views/cats/_cat.html.erb
<div id="<%= dom_id cat %>" class="card mb-3">
  <div class="card-body">
    <p class="card-text">
      <strong>Name:</strong>
      <%= cat.name %>
    </p>

    <p class="card-text">
      <strong>Color:</strong>
      <%= cat.color %>
    </p>
  </div>
</div>

app/views/cats/_form.html.erb
<%= form_with(model: cat, local: true, class: "needs-validation", novalidate: true) do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true %>
    <div class="invalid-feedback">
      Please provide a name.
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :color, class: "form-label" %>
    <%= form.text_field :color, class: "form-control", required: true %>
    <div class="invalid-feedback">
      Please provide a color.
    </div>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

<script>
  (function () {
    'use strict'
    
    var forms = document.querySelectorAll('.needs-validation')

    Array.prototype.slice.call(forms)
      .forEach(function (form) {
        form.addEventListener('submit', function (event) {
          if (!form.checkValidity()) {
            event.preventDefault()
            event.stopPropagation()
          }
          
          form.classList.add('was-validated')
        }, false)
      })
  })()
</script>

app/views/cats/edit.html.erb
<% content_for :title, "Editing cat" %>

<div class="container my-5">
  <h1 class="mb-4">Editing Cat</h1>

  <%= render "form", cat: @cat %>

  <div class="mt-3">
    <%= link_to "Cancel and Return to cats", cats_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/cats/index.html.erb
<div class="container my-5">
  <h1 class="mb-4">Cats List Page</h1>
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Color</th>
        <th>Creator</th>
        <th>Actions</th>
        <th class="bg-light text-secondary">Created At</th>
        <th class="bg-light text-secondary">Updated At</th>
      </tr>
    </thead>
    <tbody>
      <% @cats.each do |cat| %>
        <tr>
          <td><%= cat.name %></td>
          <td>
            <%= display_color_block(cat.color) %>
            <%= cat.color %>
          </td>
          <td><%= link_to (cat.user ? cat.user.username : "Unknown"), (cat.user ? user_path(cat.user) : "#"), class: 'text-decoration-none' %></td>
          <td>
            <%= link_to 'Show', cat_path(cat), class: 'btn btn-info btn-sm me-2' %>
            <% if logged_in? && cat.user == current_user %>
              <%= link_to 'Edit', edit_cat_path(cat), class: 'btn btn-warning btn-sm me-2' %>  
              <%= link_to "Delete this cat", "#", data: { bs_toggle: "modal", bs_target: "#deleteModal", bs_url: cat_path(cat) }, class: "btn btn-danger btn-sm" %>
            <% end %>
          </td>
          <td class="bg-light text-secondary"><%= cat.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
          <td class="bg-light text-secondary"><%= cat.updated_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- Control Row for Pagination and Button -->
  <div class="d-flex justify-content-between align-items-center mt-3">
    <div>
    <%= link_to 'Home page', root_path, class: 'btn btn-secondary' %>
    <% if logged_in? %>
      <%= link_to "Create new cat", new_cat_path, class: 'btn btn-primary' %>
    <% end %>
    </div>
    <div>
     <%= paginate @cats %>
    </div>
  </div>
  
</div>

app/views/cats/new.html.erb
<% content_for :title, "New cat" %>

<div class="container my-5">
  <h1 class="mb-4">New Cat</h1>

  <%= render "form", cat: @cat %>

  <div class="mt-3">
    <%= link_to "Back to cats", cats_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/cats/show.html.erb
<div class="container my-5">
  <%= render @cat %>

  <div class="d-flex justify-content-start">
    <%= link_to "Back to Cats list page", cats_path, class: "btn btn-secondary mx-2" %>
    <% if logged_in? && @cat.user == current_user %>
      <%= link_to "Edit this Cat", edit_cat_path(@cat), class: "btn btn-warning mx-2" %>
      <%= link_to "Delete this cat", "#", data: { bs_toggle: "modal", bs_target: "#deleteModal", bs_url: cat_path(@cat) }, class: "btn btn-danger" %>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to 'RUBY ON RAILS DEMO', root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Users', users_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Cats
          </a>
          <ul class="dropdown-menu">
          <%= link_to 'Cat List', cats_path, class: 'dropdown-item' %>
          <% if logged_in? %>
            <%= link_to 'Create Cat', new_cat_path, class: 'dropdown-item' %>
          <% end %>
          </ul>
        </li>
        <% if logged_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.username %> <i class="bi bi-person-circle"></i>
              </a>
              <ul class="dropdown-menu">
                <%= link_to 'Profile', user_path(current_user), class: 'dropdown-item' %>
                <li><hr class="dropdown-divider"></li>
                <%= button_to "Logout", logout_path, method: :delete, form: { class: "dropdown-item-button" }, class: "dropdown-item text-start", form_class: "d-inline" %>
              </ul>
            </li>
        <% else %>
            <li class="nav-item">
              <%= link_to 'Log in', login_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', signup_path, class: 'nav-link' %>
            </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ruby V2" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>

      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show float-alert" role="alert">
          <%= message %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </div>
    <%= yield %>
  </body>

  <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Confirm Deletion</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete this cat?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <%= button_to "Delete", "#", method: :delete, class: "btn btn-danger", id: "confirmDeleteButton" %>
      </div>
    </div>
  </div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    var deleteModal = document.getElementById('deleteModal')
    deleteModal.addEventListener('show.bs.modal', function (event) {
      var button = event.relatedTarget
      var url = button.getAttribute('data-bs-url')
      var confirmButton = deleteModal.querySelector('#confirmDeleteButton')
      confirmButton.setAttribute('formaction', url)
    })
  })
</script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    var form = document.querySelector(".needs-validation");
    form.addEventListener('submit', function (event) {
      var password = document.getElementById('password');
      var confirmation = document.getElementById('password_confirmation');

      if (password.value !== confirmation.value) {
        event.preventDefault();
        event.stopPropagation();
        alert('Passwords do not match.');
        confirmation.classList.add('is-invalid');
      } else {
        confirmation.classList.remove('is-invalid');
      }
    }, false);
  });
</script>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the About page</h1>

<%= link_to 'Cats List', cats_path %> 
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="p-5 mb-4 bg-jumbotron rounded-3 text-center position-relative text-white" style="background-image: url(<%= asset_path('bg-cats.jpg') %>); background-size: cover; background-position: center; background-repeat: no-repeat;">
      <div class="container-fluid py-5 d-flex flex-column align-items-center position-relative">
        <h1 class="display-5 fw-bold">Custom jumbotron</h1>
        <p class="col-md-8 fs-4 text-center">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <%= link_to 'Sign up !', signup_path, class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
</div>
</div>
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Ruby Project Demo</small>
   </div>
</footer>

app/views/users/_form.html.erb
<div class="card">
  <div class="card-header">
    <h2><%= content_for?(:title) ? yield(:title) : "User Form" %></h2>
  </div>
  <div class="card-body">
    <%= form_with(model: user, local: true, class: "needs-validation", novalidate: true) do |form| %>
      <% if user.errors.any? %>
      <div class="alert alert-danger">
        <h4 class="alert-heading"><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h4>
          <ul>
            <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
      </div>
      <% end %>
      <div class="mb-3">
        <%= form.label :username, class: "form-label" %>
        <%= form.text_field :username, class: "form-control", required: true %>
        <div class="invalid-feedback">
          Please provide a valid username.
        </div>
      </div>

      <div class="mb-3">
        <%= form.label :email, class: "form-label" %>
        <%= form.email_field :email, class: "form-control", required: true %>
        <div class="invalid-feedback">
          Please provide a valid email.
        </div>
      </div>

      <div class="mb-3">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, id: 'password', class: "form-control", required: true %>
        <div class="invalid-feedback">
          Please provide a valid password.
        </div>
      </div>

      <div class="mb-3">
        <%= form.label :password_confirmation, class: "form-label" %>
        <%= form.password_field :password_confirmation, id: 'password_confirmation', class: "form-control", required: true %>
        <div class="invalid-feedback">
          Please confirm your password.
        </div>
      </div>

      <div class="mb-4">
        <%= form.submit "Sign up", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_user.html.erb
<div class="user mb-3">
  <div class="card">
    <div class="card-body text-center">
      <%= gravatar_for user, size: 80 %> 
      <h3 class="mt-2"><%= user.username %></h3>
      <p><%= user.email %></p>
      <%= link_to "Show this user", user_path(user), class: 'btn btn-info' %>
    </div>
  </div>
</div>

app/views/users/_user_details.html.erb
<div id="<%= dom_id user %>" class="card shadow-lg text-center">
  <div class="card-body p-0">
    <%= gravatar_for user %>
    <div class="card-header bg-primary text-white">
      <h2><%= user.username %> Profile</h2>
    </div>
    <div class="card-body">
      <h5 class="card-title">
        <strong>Username:</strong> <%= user.username %>
      </h5>
      <p class="card-text">
        <strong>Email:</strong> <%= user.email %>
      </p>
      <p class="card-text">
        <strong>Account Created:</strong> <%= user.created_at.strftime("%B %d, %Y") %>
      </p>
      <% if current_user == user %>
        <%= link_to "Edit this user", edit_user_path(user), class: "btn btn-primary" %>
      <% end %>
      <%= link_to "Back to users", users_path, class: "btn btn-secondary" %>
    </div>
    <hr>
    <div class="card-footer">
      <h3 class="card-title">Cats Created by <%= user.username %></h3>
      <% if user.cats.any? %>
        <div class="row justify-content-center">
          <% user.cats.each do |cat| %>
            <div class="col-md-4 mb-4">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title"><%= cat.name %></h5>
                  <%= link_to 'Show', cat_path(cat), class: 'btn btn-sm btn-info' %>
                  <% if current_user == user %>
                    <%= link_to 'Edit', edit_cat_path(cat), class: 'btn btn-sm btn-warning' %>
                    <%= link_to "Delete this cat", "#", data: { bs_toggle: "modal", bs_target: "#deleteModal", bs_url: cat_path(cat) }, class: "btn btn-sm btn-danger" %>
                  <% end %>
                </div>
              </div>
            </div>
            <% if ((user.cats.index(cat) + 1) % 3 == 0) && (user.cats.index(cat) + 1 != user.cats.size) %>
              <div class="w-100"></div> 
            <% end %>
          <% end %>
        </div>
      <% else %>
        <p>No cats found.</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<% content_for :title, "Edit your profile" %>

<div class="container my-4">
  <%= render 'form', user: @user %>

  <div class="mt-4">
    <%= link_to "Back to users", users_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Users" %>

<h1 class="text-center mt-4">User List</h1>

<div id="users" class="container">
  <div class="row justify-content-center">
    <% @users.each do |user| %>
      <div class="col-md-6 col-lg-4 mb-4">
        <%= render 'user', user: user %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% content_for :title, "Sign up for RUBY DEMO" %>

<div class="container my-4">
  <%= render 'form', user: @user %>

  <div class="mt-4">
    <%= link_to "Back to users", users_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <%= render 'user_details', user: @user %>
</div>